name: BuildMaster.yml

on:
  push:
    branches:
      - main

env:
  azure_artifacts_feed_url: https://pkgs.dev.azure.com/frends-platform/frends-tasks/_packaging/test/nuget/v3/index.json

jobs:
  build:
    name: Build master on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Pack release version
      run: dotnet pack --configuration Release
    
    # Setup dotnet again with prod feed
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        source-url: ${{ env.azure_artifacts_feed_url }}
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.TASKS_FEED_API_KEY }} 
    - name: Push NuGet package(s) to the prod feed
      run: dotnet nuget push bin/Release/frendstasktemplate.*.nupkg --api-key ${{ secrets.TASKS_FEED_API_KEY }} --source ${{ env.azure_artifacts_feed_url }}

